### ISSUE TITLE
Additional list of domains returning "expired" when they're not

### ISSUE THREAD

**Issue by RichwebInc** [nixcraft/domain-check-2#13]
Looks like we've got some additional extensions not quite supported as of 2.10 (or 2.17). :)
.aero
.asia
.cc
.college

**Comment by happyoccasion** [comment]
This is not really a bug, to handle this you'll have to give a domain of each TLD. The root cause is that many whois-servers returns the data in different formating. The script only knows how to handle whois-servers it has rulesets for. I tried to look at the first one (.asia) but it did not return any relevant data:

```
~ whois dot.asia
[Querying whois.nic.asia]
[whois.nic.asia]
Reserved by DotAsia
>>> Last update of WHOIS database: 2018-01-04T13:14:40Z <<<

Access to WHOIS information is provided to assist persons in determining the contents of a domain name registration record in the registry database. The data in this record is provided by The Registry Operator for informational purposes only, and accuracy is not guaranteed.  This service is intended only for query-based access. You agree that you will use this data only for lawful purposes and that, under no circumstances will you use this data to: (a) allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the data recipient's own existing customers; or (b) enable high volume, automated, electronic processes that send queries or data to the systems of Registry Operator, a Registrar, or Afilias except as reasonably necessary to register domain names or modify existing registrations. All rights reserved. Registry Operator reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.
```

If you could provide domains I'll have a look at it.

**Comment by RichwebInc** [comment]
Unfortunately, due to our Customer Privacy policy, I am unable to provide any domains. I didn't intend to file this as a bug. Rather, I was requesting that support for those TLDs be added into the script. :)

Thanks!

**Comment by happyoccasion** [comment]
Could be me misinterpreting you. :100: 

If you could find some domains that are NOT your customers that would be great. Otherwise I'll look into when I find the time.

**Comment by RichwebInc** [comment]
hello.aero
visit.asia
my.cc

Since the .college customer is a public educational institution, I will bypass the privacy policy here:
rcc.college

I also caught a couple others that had issues returning results:
.biz (workathome.biz)
.co (fi.co)

All websites do work, so you should be able to pull whois info. :)

**Comment by nixcraft** [comment]
I will look into this as soon as I finish with ongoing crazy stuff with CPU bugs.

**Comment by nixcraft** [comment]
Check the latest version. It support all those domain names now.
