### ISSUE TITLE
Please add support for .de domains

### ISSUE THREAD

**Issue by wowcut** [nixcraft/domain-check-2#19]
WOuld be great to see this nice script working with .de domains. 
I am not sure I understand what exactly to add, but it looks not too complicated, so I allow myself to post this as a feature request... thanks!

**Comment by nixcraft** [comment]
.de doesn't provide expiry date info for given domain name. For example:
`whois google.de`
It just returns 
<pre>Domain: google.de
Nserver: ns1.google.com
Nserver: ns2.google.com
Nserver: ns3.google.com
Nserver: ns4.google.com
Status: connect
Changed: 2018-03-12T21:44:25+01:00</pre>
There is no expiry or creation date info.
