### ISSUE TITLE
.ro domains are giving wrong results

### ISSUE THREAD

**Issue by dragosboroianu** [nixcraft/domain-check-2#22]
First of all, you guys are doing an awesome job and thank you so much for all your work! :)

The issue I encountered is pretty simple, when checking .ro domains, I get a wrong expiration date:

[root@srv ~]# domain-check-2 -d google.ro
Domain                              Registrar                                      Status   Expires     Days Left
----------------------------------- ---------------------------------------------- -------- ----------- 
google.ro                           MarkMonitor Inc.                               Expired              -2458480
[root@srv ~]#

Have any idea if this is related to my server or maybe is something that can be fixed on the script code?

Thanks again for everything - have a good one and happy holidays!

**Comment by nixcraft** [comment]
I need to know whois server name.

**Comment by dragosboroianu** [comment]
Hey! the whois server for .ro domains should be whois.rotld.ro. Thank you for your time!

**Comment by nixcraft** [comment]
I am not getting any response from that whois server:
```
whois -h whois.rotld.ro google.ro
```

**Comment by dragosboroianu** [comment]
Indeed, from my personal computer IP address I can't use that whois server - probably my IP si blocked by them ( the .ro registrat RoTLD). However, one of my VPSs that has a different IP, I can use that and here are the results:

```
[root@server-bucharest ~]# whois -h whois.rotld.ro google.ro
[Querying whois.rotld.ro]
[whois.rotld.ro]

% The WHOIS service offered by ROTLD and the access to the records in the ROTLD WHOIS database 
% are provided for information purposes and to be used within the scope of technical or administrative
% necessities of Internet operation or to remedy legal problems. The use for other purposes, 
% in particular for advertising and domain hunting, is not permitted.

% Without prejudice to the above, it is explicitly forbidden to extract, copy and/or use or re-utilise
% in any form and by any means (electronically or not) the whole or a quantitatively or qualitatively 
% substantial part of the contents of the WHOIS database without prior and explicit permission by ROTLD, 
% nor in any attempt hereof, to apply automated, electronic processes to ROTLD (or its systems).

% ROTLD cannot, under any circumstances, be held liable in case the stored information would prove 
% to be wrong, incomplete or not accurate in any sense.

% You agree that any reproduction and/or transmission of data for commercial purposes will always 
% be considered as the extraction of a substantial part of the content of the WHOIS database.

% By submitting the query you agree to abide by this policy and accept that ROTLD can take measures 
% to limit the use of its WHOIS services in order to protect the privacy of its registrants or the 
% integrity of the database.

% The ROTLD WHOIS service on port 43 never discloses any information concerning the registrant.

% Registrant information can be obtained through use of the web-based whois service available from 
% the ROTLD website www.rotld.ro


  Domain Name: google.ro
  Registered On: 2000-07-17
  Expires On: 2019-09-17
  Registrar: MarkMonitor Inc.
  Referral URL: www.markmonitor.com

  DNSSEC: Inactive

  Nameserver: ns1.google.com
  Nameserver: ns2.google.com
  Nameserver: ns3.google.com
  Nameserver: ns4.google.com

  Domain Status: UpdateProhibited


[root@server-bucharest ~]#
```

**Comment by nixcraft** [comment]
Alright. It should work based upon above outputs. Grab the latest version and try out.
<pre>
Domain                              Registrar                                      Status   Expires     Days Left
----------------------------------- ---------------------------------------------- -------- ----------- ---------
google.ro                           MarkMonitor Inc.                               Valid    17-sep-2019   253  
</pre>

**Comment by dragosboroianu** [comment]
Indeed, it works now! Thank you very much for your great work!
