### ISSUE TITLE
@hawkeye116477 Try adding `export LC_ALL=en_US.UTF-8` to the top of the script. That should make the `date` commands input/output the dates in English.

### ISSUE THREAD

**Issue by click0** [nixcraft/domain-check-2#32]
@hawkeye116477 Try adding `export LC_ALL=en_US.UTF-8` to the top of the script. That should make the `date` commands input/output the dates in English.

Edit: I tested it again with the two new TLDs that were added to this script (https://github.com/nixcraft/domain-check-2/pull/25/commits/4c3b2fee985b8c35f7b23a3e4899dc3818a521ee and https://github.com/nixcraft/domain-check-2/pull/25/commits/ead6a678f434a1f27a24fbaf9fe629362b6ccb7c) and my script still works without any changes. Here is the updated screenshot from my script:
![image](https://user-images.githubusercontent.com/15305150/60161815-19d47080-97ad-11e9-8934-6396caa9798c.png)

_Originally posted by @tdulcet in https://github.com/nixcraft/domain-check-2/pull/25#issuecomment-502621737_

**Comment by hawkeye116477** [comment]
Not mention me and not repeat, I saw what tdulcet wrote...
