### ISSUE TITLE
Add support for french domains (FR and others)

### ISSUE THREAD

**Issue by jherazob** [nixcraft/domain-check-2#8]
The whois service for french domain names (.fr, .re, .tf, .yt, .pm and .wf) is managed by [AFNIC](https://www.afnic.fr/en/products-and-services/services/whois/), server at whois.afnic.fr. Hopefully adding these should be simple.

**Comment by nixcraft** [comment]
Can you give a list of domain list? Like google.fr , for rest of the domains?

**Comment by jherazob** [comment]
I only interact with .fr domains, sorry

**Comment by happyoccasion** [comment]
@jherazob this is in pull request #9

**Comment by nixcraft** [comment]
I fixed .fr/.re and other domain names in the latest version. Try out and let me know
